### ISSUE TITLE
`/ajax/game/:id/removeSet` fails

### ISSUE THREAD

**Issue by tjhorner** [Rylius/CardsAgainstEquestria#134]
Just breaks. Stack trace (why do you have this in prod, lol):

```
TypeError: Object function (obj) {
    if (obj instanceof _) return obj;
    if (!(this instanceof _)) return new _(obj);
    this._wrapped = obj;
  } has no method 'findIndex'
    at removeSet (/var/www/cardsagainstequestria.com/routes/ajax/game.js:169:19)
    at callbacks (/var/www/cardsagainstequestria.com/node_modules/express/lib/router/index.js:164:37)
    at param (/var/www/cardsagainstequestria.com/node_modules/express/lib/router/index.js:138:11)
    at param (/var/www/cardsagainstequestria.com/node_modules/express/lib/router/index.js:135:11)
    at pass (/var/www/cardsagainstequestria.com/node_modules/express/lib/router/index.js:145:5)
    at Router._dispatch (/var/www/cardsagainstequestria.com/node_modules/express/lib/router/index.js:173:5)
    at Object.router (/var/www/cardsagainstequestria.com/node_modules/express/lib/router/index.js:33:10)
    at next (/var/www/cardsagainstequestria.com/node_modules/express/node_modules/connect/lib/proto.js:193:15)
    at Object.handle (/var/www/cardsagainstequestria.com/app.js:208:5)
    at next (/var/www/cardsagainstequestria.com/node_modules/express/node_modules/connect/lib/proto.js:193:15)
```

**Comment by Rylius** [comment]
Yay for express ignoring my options

Apparently findIndex was added to Underscore in a later version but the docs didn't mention it? Updated Underscore, let's see how that works

**Comment by tjhorner** [comment]
Maybe now you should make it not show stack traces in production? It's pretty unsafe that way...

**Comment by Rylius** [comment]
Since the entire code is on here anyway the only information you gain is the application folder... which really doesn't help you with anything. :)
But yeah, shouldn't be showing, not entirely sure what's going on there

**Comment by tjhorner** [comment]
Well... some other problem might come along and your database credentials or some other important thing might be leaked!

**Comment by Rylius** [comment]
Nah, database issues just crash the entire site, I checked

**Comment by tjhorner** [comment]
Something else might access the config, and if the property doesn't exist, it would show the config in the stack trace (or would it just show "[Object object]"?)

**Comment by Rylius** [comment]
"undefined" everywhere.

Based on the it shouldn't be adding the stack trace handler at all... this is really weird

**Comment by Rylius** [comment]
Commented out the error handler, need to investige once I get back from work. Ugh

**Comment by Rylius** [comment]
Just confirmed the actual issue to be fixed

**Comment by tjhorner** [comment]
On topic of the error handler, it's not extremely important so you don't need to stress about it lol

**Comment by Rylius** [comment]
It's what leaks the stack trace and object states. :P
Going to take a closer look later tonight
