### ISSUE TITLE
Crash in global chat

### ISSUE THREAD

**Issue by Rylius** [Rylius/CardsAgainstEquestria#91]
throw new Error('Can\'t set headers after they are sent.');
          ^
    Error: Can't set headers after they are sent.
        at ServerResponse.OutgoingMessage.setHeader (http.js:707:11)
        at ServerResponse.res.setHeader (/var/www/cardsagainstequestria.com/node_modules/express/node_modules/connect/lib/patch.js:63:22)
        at ServerResponse.res.set.res.header (/var/www/cardsagainstequestria.com/node_modules/express/lib/response.js:527:10)
        at ServerResponse.res.contentType.res.type (/var/www/cardsagainstequestria.com/node_modules/express/lib/response.js:396:15)
        at ServerResponse.res.send (/var/www/cardsagainstequestria.com/node_modules/express/lib/response.js:112:14)
        at /var/www/cardsagainstequestria.com/lib/chat.js:90:26
        at Array.forEach (native)
        at Function._.each._.forEach (/var/www/cardsagainstequestria.com/node_modules/underscore/underscore.js:79:11)
        at /var/www/cardsagainstequestria.com/lib/chat.js:88:11
        at Array.forEach (native)

please don't be a race condition please don't be a race condition please don't be a race condition please don't be a race condition please don't be a race condition please don't be a race condition please don't be a race condition please don't be a race condition

**Comment by Rylius** [comment]
Haven't seen this happening in a year, closing for now.
